query_reward_type: ndcg
listwise_reward_type: ndcg
query_reward_ndcg_k: 10
listwise_reward_ndcg_k: 16
query_mixed_contrastive_weight: 1.0
query_mixed_ndcg_weight: 1.0
listwise_mixed_contrastive_weight: 1.0
listwise_mixed_ndcg_weight: 1.0
query_contrastive_use_in_batch_negatives: false
listwise_contrastive_use_in_batch_negatives: false
query_relevance_scheme: binary
listwise_relevance_scheme: graded
