mteb_eval_tasks: null
mteb_eval_benchmark: null
mteb_eval_langs: null
mteb_eval_output_dir: null
mteb_eval_batch_size: 16
mteb_eval_precision: fp16
mteb_eval_model_kwargs: null
mteb_eval_encode_kwargs: null
mteb_eval_run_kwargs: null
